In [1]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [ ]:
true = pd.read_csv('../data/True.csv')
fake = pd.read_csv('../data/Fake.csv')

In [ ]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true['label']=1

In [ ]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [ ]:
fake['label']=0

In [ ]:
fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [ ]:
news = pd.concat([fake, true],axis=0)

In [ ]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [ ]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [ ]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [ ]:
news.drop(['title','subject','date'],axis=1)

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

[44898 rows x 2 columns]

In [ ]:
news = news.sample(frac=1)

In [ ]:
news.head()

,title,text,subject,date,label
11408,HILARIOUS! Look Who LIBERAL Middlebury Profess...,"Two weeks ago at Middlebury College, Charles M...",politics,"Mar 14, 2017",0
7783,Another Progressive Democrat Lines Up Behind ...,Probably the most highly coveted endorsement b...,News,"February 29, 2016",0
3778,Trump’s Selfishness Is Already KILLING Busine...,Donald Trump has his staff working on the logi...,News,"November 17, 2016",0
17359,U.S.-led anti-Islamic State coalition says Ira...,BAGHDAD (Reuters) - The U.S.-led anti-Islamic ...,worldnews,"October 16, 2017",1
23101,Obama Joins Comedy Central Host to Push ‘Laugh...,21st Century Wire says President Obama is once...,Middle-east,"December 15, 2016",0

In [ ]:
news.tail()

,title,text,subject,date,label
13649,JIMMY FALLON Brings On “Little Donald” To Be H...,This teen has a pretty good impression of Dona...,politics,"Jun 23, 2016",0
9220,Three teenagers arrested over assaults during ...,(Reuters) - Three teenagers were arrested on W...,politicsNews,"June 9, 2016",1
16451,Taiwan president calls for breakthrough in Chi...,TAIPEI (Reuters) - Taiwan and China need to dr...,worldnews,"October 26, 2017",1
15691,Thousands march against coal ahead of climate ...,FRANKFURT (Reuters) - Thousands of people took...,worldnews,"November 4, 2017",1
1763,Former Trump adviser Flynn's son being probed ...,WASHINGTON (Reuters) - The son of U.S. Preside...,politicsNews,"September 13, 2017",1

In [ ]:
news.reset_index(inplace=True)

In [ ]:
news.head()

,index,title,text,subject,date,label
0,11408,HILARIOUS! Look Who LIBERAL Middlebury Profess...,"Two weeks ago at Middlebury College, Charles M...",politics,"Mar 14, 2017",0
1,7783,Another Progressive Democrat Lines Up Behind ...,Probably the most highly coveted endorsement b...,News,"February 29, 2016",0
2,3778,Trump’s Selfishness Is Already KILLING Busine...,Donald Trump has his staff working on the logi...,News,"November 17, 2016",0
3,17359,U.S.-led anti-Islamic State coalition says Ira...,BAGHDAD (Reuters) - The U.S.-led anti-Islamic ...,worldnews,"October 16, 2017",1
4,23101,Obama Joins Comedy Central Host to Push ‘Laugh...,21st Century Wire says President Obama is once...,Middle-east,"December 15, 2016",0

In [ ]:
news.drop(['index'],axis=1, inplace=True)

In [ ]:
news.head()

,title,text,subject,date,label
0,HILARIOUS! Look Who LIBERAL Middlebury Profess...,"Two weeks ago at Middlebury College, Charles M...",politics,"Mar 14, 2017",0
1,Another Progressive Democrat Lines Up Behind ...,Probably the most highly coveted endorsement b...,News,"February 29, 2016",0
2,Trump’s Selfishness Is Already KILLING Busine...,Donald Trump has his staff working on the logi...,News,"November 17, 2016",0
3,U.S.-led anti-Islamic State coalition says Ira...,BAGHDAD (Reuters) - The U.S.-led anti-Islamic ...,worldnews,"October 16, 2017",1
4,Obama Joins Comedy Central Host to Push ‘Laugh...,21st Century Wire says President Obama is once...,Middle-east,"December 15, 2016",0

In [ ]:
news = news.drop(['title','subject','date'],axis=1)

In [ ]:
news.head()

                                                text  label
0  Two weeks ago at Middlebury College, Charles M...      0
1  Probably the most highly coveted endorsement b...      0
2  Donald Trump has his staff working on the logi...      0
3  BAGHDAD (Reuters) - The U.S.-led anti-Islamic ...      1
4  21st Century Wire says President Obama is once...      0

In [ ]:
import re
import nltk
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Jayaprakash V
[nltk_data]     K\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [ ]:
stop_words = set(stopwords.words('english'))

In [ ]:
def clean_text(text):
    # convert to lowercase
    text = text.lower()
    
    # remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    
    # remove content inside brackets (like (Reuters), (VIDEO))
    text = re.sub(r'\(.*?\)', '', text)
    
    # remove non-alphabet characters (keep only letters)
    text = re.sub(r'[^a-z\s]', '', text)
    
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # remove stopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]

    # remove html tags
    text = re.sub(r'<.*?>', '', text)

    # remove newline characters
    text = re.sub(r'\n', ' ', text)
    
    return " ".join(words)

In [ ]:
news['text'] = news['text'].apply(clean_text)

In [ ]:
news.head()

                                                text  label
0  two weeks ago middlebury college charles murra...      0
1  probably highly coveted endorsement either dem...      0
2  donald trump staff working logistics allowing ...      0
3  baghdad usled antiislamic state coalition said...      1
4  st century wire says president obama appearing...      0

In [ ]:
x = news['text']
y = news['label']

In [ ]:
x

0        two weeks ago middlebury college charles murra...
1        probably highly coveted endorsement either dem...
2        donald trump staff working logistics allowing ...
3        baghdad usled antiislamic state coalition said...
4        st century wire says president obama appearing...
                               ...
44893    teen pretty good impression donald trumpjack a...
44894    three teenagers arrested wednesday accused thr...
44895    taipei taiwan china need drop historical bagga...
44896    frankfurt thousands people took streets bonn s...
44897    washington son us president donald trumps form...
Name: text, Length: 44898, dtype: str

In [ ]:
y

0        0
1        0
2        0
3        1
4        0
        ..
44893    0
44894    1
44895    1
44896    1
44897    1
Name: label, Length: 44898, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
x_train.shape

(31428,)

In [ ]:
x_test.shape

(13470,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

In [ ]:
xv_train = vectorizer.fit_transform(x_train)
xv_test = vectorizer.transform(x_test)

In [ ]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3943776 stored elements and shape (31428, 5000)>

In [ ]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1693987 stored elements and shape (13470, 5000)>

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(xv_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(xv_test)

In [ ]:
model.score(xv_test, y_test)

0.9805493689680772

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      7035
           1       0.98      0.98      0.98      6435

    accuracy                           0.98     13470
   macro avg       0.98      0.98      0.98     13470
weighted avg       0.98      0.98      0.98     13470

## Decision Tree Model

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(xv_train, y_train)

In [ ]:
dt_pred = dt_model.predict(xv_test)
dt_score = dt_model.score(xv_test, y_test)
print(f'Decision Tree Accuracy: {dt_score:.4f}')

In [ ]:
print('Decision Tree Classification Report:')
print(classification_report(y_test, dt_pred))

## Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(xv_train, y_train)

In [ ]:
rf_pred = rf_model.predict(xv_test)
rf_score = rf_model.score(xv_test, y_test)
print(f'Random Forest Accuracy: {rf_score:.4f}')

In [ ]:
print('Random Forest Classification Report:')
print(classification_report(y_test, rf_pred))

## Model Comparison

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = ['Logistic Regression', 'Decision Tree', 'Random Forest']
preds  = [y_pred, dt_pred, rf_pred]

results = []
for name, pred in zip(models, preds):
    results.append({
        'Model':     name,
        'Accuracy':  accuracy_score(y_test, pred),
        'Precision': precision_score(y_test, pred),
        'Recall':    recall_score(y_test, pred),
        'F1 Score':  f1_score(y_test, pred),
    })

comparison_df = pd.DataFrame(results)
comparison_df = comparison_df.set_index('Model')
print(comparison_df.round(4))

In [ ]:
# Bar chart comparison
metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
x = range(len(metrics))
width = 0.25

fig, ax = plt.subplots(figsize=(10, 6))

colors = ['#4C72B0', '#DD8452', '#55A868']
for i, (model_name, row) in enumerate(comparison_df.iterrows()):
    vals = [row[m] for m in metrics]
    bars = ax.bar([xi + i*width for xi in x], vals, width, label=model_name, color=colors[i])
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                f'{val:.3f}', ha='center', va='bottom', fontsize=8)

ax.set_xlabel('Metric')
ax.set_ylabel('Score')
ax.set_title('Model Comparison — Fake News Detection')
ax.set_xticks([xi + width for xi in x])
ax.set_xticklabels(metrics)
ax.set_ylim(0.85, 1.02)
ax.legend()
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

In [ ]:
# Confusion matrices side by side
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

for ax, name, pred in zip(axes, models, preds):
    cm = confusion_matrix(y_test, pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fake', 'True'])
    disp.plot(ax=ax, colorbar=False, cmap='Blues')
    ax.set_title(name)

plt.suptitle('Confusion Matrices', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()